name: main

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4

    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: "latest"
        environment-file: conda/env.yaml
        channels: conda-forge,nodefaults
        activate-environment: compose
        auto-update-conda: true
        conda-solver: libmamba
        python-version: "3.11"

    - name: Install package
      run: |
          poetry build
          poetry install
          pip install $(ls dist/compose_go*tar.gz)

    - name: Test cmd & binary
      run: make smoke-test
